SIDUKM.WebUI/Controllers/MessageController.cs
using System;
using System.Web.Mvc;
using SIDUKM.Domain;
using SIDUKM.Logic;
using SIDUKM.WebUI.Infrastructure;
using SIDUKM.WebUI.Models.Message;

namespace SIDUKM.WebUI.Controllers
{
    public class MessageController : AbstractController
    {

        private IMessageService MessageService;
        private ISpottedService SpottedService;

        public MessageController(ISessionManager sessionManager, IAccountService accountService, 
            IMailService mailService, IMessageService messageService, ISpottedService spottedService) 
            : base(sessionManager, accountService, mailService)
        {
            MessageService = messageService;
            SpottedService = spottedService;
        }

        public ActionResult Send(int? original, int? topic, int? user)
        {
            var model = new SendViewModel()
            {
                ReturnLink = Request.ServerVariables["HTTP_REFERER"]
            };
            if (user.HasValue)
            {
                model.AccountId = user.Value.ToString();
                model.AccountName = AccountService.GetAccountName(user.Value, true);
            }
            else if (original.HasValue)
            {
                var msg = MessageService.GetRawMessage(original.Value);
                if (msg.Recipient_AccountID != AccountService.GetAccountId(HttpContext.User.Identity.Name))
                {
                    return HttpNotFound();
                }
                model.AccountId = msg.Sender_AccountID.ToString();
                model.AccountName = AccountService.GetAccountName(msg.Sender_AccountID, true);
                model.Subject = string.Format("Re: {0}", msg.Subject);
                model.Content = string.Format("\n-- Oryginalna wiadomość: --\n{0}", msg.Content);
            }
            else if (topic.HasValue)
            {
                var source = SpottedService.GetRawTopic(topic.Value);
                model.AccountId = "-1";
                model.AnonymousSourceId = source.TopicId;
                model.AccountName = source.IsAnonymous
                    ? "<< anonimowy >>"
                    : AccountService.GetAccountName(source.AccountId, true);
            }
            else
            {
                model.AccountList = MessageService.GetAccountsList();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Send(SendViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Message msg = new Message
            {
                Content = model.Content,
                Subject = model.Subject,
                Sender_AccountID = AccountService.GetAccountId(HttpContext.User.Identity.Name),
                IsAnonymousRecipient = model.AnonymousSourceId > 0,
                Recipient_AccountID =
                    model.AnonymousSourceId > 0
                        ? SpottedService.GetRawTopic(model.AnonymousSourceId).AccountId
                        : Int32.Parse(model.AccountId)
            };
            bool result = MessageService.SendMessage(msg);
            if (result) 
            {
                //return Content("Wysłano"); // TODO: redirect na listę wiadomości 
                return RedirectToAction("List", new {folder = 1, sent = 1});
            }
            ViewBag.Error = "Wystąpił niezidentyfikowany błąd. Przepraszamy!";
            if (model.AnonymousSourceId == 0 && model.AccountName != null)
            {
                model.AccountList = MessageService.GetAccountsList();
            }
            return View(model);
        }

        public ContentResult GetUnread()
        {
            return
                Content(
                    MessageService.GetUnreadCount(AccountService.GetAccountId(HttpContext.User.Identity.Name))
                        .ToString());
        }

        public ActionResult List(int? folder = 0, int? sent = 0)
        {
            ViewBag.Site = folder;
            ViewBag.Sent = sent.HasValue ? sent : 0;
            return View();
        }

        public JsonResult GetInbox()
        {
            var collection = MessageService.GetInbox(AccountService.GetAccountId(HttpContext.User.Identity.Name));
            var parser = new DataTablesParser.DataTablesParser<MessageData>(Request, collection);
            return Json(parser.Parse());
        }

        public JsonResult GetSent()
        {
            var collection = MessageService.GetSent(AccountService.GetAccountId(HttpContext.User.Identity.Name));
            var parser = new DataTablesParser.DataTablesParser<MessageData>(Request, collection);
            return Json(parser.Parse());
        }

        public JsonResult GetTrash()
        {
            var collection = MessageService.GetDeleted(AccountService.GetAccountId(HttpContext.User.Identity.Name));
            var parser = new DataTablesParser.DataTablesParser<MessageData>(Request, collection);
            return Json(parser.Parse());
        }

        public ActionResult View(int id)
        {
            if (id > 0)
            {
                int account = AccountService.GetAccountId(HttpContext.User.Identity.Name);
                var msg = MessageService.GetMessage(id, account);
                if (msg != null)
                {
                    ViewBag.link = Request.ServerVariables["HTTP_REFERER"];
                    //int account = AccountService.GetAccountId(HttpContext.User.Identity.Name);
                    if (msg.SenderId == account || msg.RecipientId == account)
                    {
                        if (msg.RecipientId == account)
                        {
                            MessageService.CheckAsRead(id);
                        }
                        return View(msg);
                    }
                }
            }
            return HttpNotFound();
        }

        public ActionResult Delete(int id)
        {
            var referer = Request.ServerVariables["HTTP_REFERER"];
            var result = MessageService.RemoveMessage(id, AccountService.GetAccountId(HttpContext.User.Identity.Name));
            return Redirect(referer);
        }

        public ActionResult Undelete(int id)
        {
            var referer = Request.ServerVariables["HTTP_REFERER"];
            var result = MessageService.UnremoveMessage(id, AccountService.GetAccountId(HttpContext.User.Identity.Name));
            return Redirect(referer);
        }

        public ActionResult DeleteFromTrash(int id)
        {
            var result = MessageService.RemoveFromTrash(id, AccountService.GetAccountId(HttpContext.User.Identity.Name));
            return RedirectToAction("List", new { folder = 2 });
        }
    }
}

SIDUKM.WebUI/Controllers/StatsController.cs
using System.Linq;
using System.Web.Mvc;
using SIDUKM.Logic;
using SIDUKM.WebUI.Infrastructure;

namespace SIDUKM.WebUI.Controllers
{
    public class StatsController : AbstractController
    {
        IStatService StatService { get; set; }

        public StatsController(ISessionManager sessionManager, IAccountService accountService, IMailService mailService,
            IStatService statService) : base(sessionManager, accountService, mailService)
        {
            StatService = statService;
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetRegistrationsPerDay(int acc = 0)
        {
            var result = acc == 0
                ? StatService.RegistrationsPerDay().OrderBy(x => x.Key)
                : StatService.StatAccumulated(StatService.RegistrationsPerDay)
                    .OrderBy(x => x.Key);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetTopicsPerDay(int acc = 0)
        {
            var result = acc == 0
                ? StatService.SpottedTopicsPerDay().OrderBy(x => x.Key)
                : StatService.StatAccumulated(StatService.SpottedTopicsPerDay)
                    .OrderBy(x => x.Key);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetPostsPerDay(int acc = 0)
        {
            var result = acc == 0
                ? StatService.SpottedPostsPerDay().OrderBy(x => x.Key)
                : StatService.StatAccumulated(StatService.SpottedPostsPerDay)
                    .OrderBy(x => x.Key);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetMostCommented()
        {
            return Json(StatService.MostCommentedTopic(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetTopicVotes(int type = 1)
        {
            return type == -1
                ? Json(StatService.LowestVotesTopic(), JsonRequestBehavior.AllowGet)
                : Json(StatService.HighestVotesTopic(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetPostVotes(int type = 1)
        {
            return type == -1
                ? Json(StatService.LowestVotesPost(), JsonRequestBehavior.AllowGet)
                : Json(StatService.HighestVotesPost(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetActivity(int posts = 0, int count = 10)
        {
            return posts == 1
                ? Json(StatService.SpottedActivityByPosts(count).OrderByDescending(x => x.Value),
                    JsonRequestBehavior.AllowGet)
                : Json(StatService.SpottedActivityByTopics(count).OrderByDescending(x => x.Value),
                    JsonRequestBehavior.AllowGet);
        }
    }
}

SIDUKM.WebUI/Controllers/TransportController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Rotativa;
using Rotativa.Options;
using SIDUKM.Logic;
using SIDUKM.WebUI.Infrastructure;
using SIDUKM.WebUI.Models.Transport;

namespace SIDUKM.WebUI.Controllers
{
    public class TransportController : AbstractController
    {
        IBusService BusService { get; set; }

        public TransportController(ISessionManager sessionManager, IAccountService accountService, IMailService mailService,
            IBusService busService) : 
            base(sessionManager, accountService, mailService)
        {
            BusService = busService;
        }

        [AllowAnonymous]
        public ActionResult FindRoute()
        {
            // TODO przerobić żeby nie korzystało z jakdojade
            // TODO obsługa wielu miast
            var model = new FindRouteViewModel { Stops = BusService.GetStopsDistinct(1) };
            return View(model);
        }

        [AllowAnonymous]
        public JsonResult GetCoords(int? start, int? stop)
        {
            if (start != null && stop != null)
                return Json(new {start = BusService.GetCoordinates(start.Value), stop = BusService.GetCoordinates(stop.Value)},
                    JsonRequestBehavior.AllowGet);
            return Json(null, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult LinesList()
        {
            //var model = BusService.GetLines(1);
            LineViewModel model = new LineViewModel()
            {
                LineNames = BusService.GetLineNames(1)
            };

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult DirectionsList(string lineName)
        {
            ViewBag.Return = Request.ServerVariables["HTTP_REFERER"];
            DirectionsViewModel model = new DirectionsViewModel()
            {
                DirectionsName = BusService.GetDirectionByName(lineName),
                LineName = lineName
            };
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult StopList(int? id)
        {
            
            if (id.HasValue)
            {
                //ViewBag.Return = Request.ServerVariables["HTTP_REFERER"];
                var name = BusService.GetLineName(id.Value);
                ViewBag.Return = Url.Action("DirectionsList", new {lineName = name});
                //var model = BusService.GetStopsByLine(id.Value);
                var model = BusService.GetStopsOrder(id.Value);

                return View(model);
            }

            return RedirectToAction("LinesList");
        }

        [AllowAnonymous]
        public ActionResult Timetable(int? lineId, int? stopId)
        {
            if (lineId.HasValue && stopId.HasValue)
            {
                ViewBag.Return = Request.ServerVariables["HTTP_REFERER"];
                var lineName = BusService.GetLineNameWithStopName(lineId.Value, stopId.Value);
                var model =
                    new Tuple<Dictionary<string, List<string>>, string>(
                        BusService.GetTimetableParsed(lineId.Value, stopId.Value), lineName);
                ViewBag.lineId = lineId.Value;
                ViewBag.stopId = stopId.Value;
                return View(model);
            }

            return RedirectToAction("LinesList");
        }

        [AllowAnonymous]
        public ActionResult TimetableToPrint(int? lineId, int? stopId)
        {
            if (!lineId.HasValue || !stopId.HasValue)
            {
                return Content("<h1>Błąd!</h1>");
            }

            var lineName = BusService.GetLineNameWithStopName(lineId.Value, stopId.Value);
            var model =
                new Tuple<Dictionary<string, List<string>>, string>(
                    BusService.GetTimetableParsed(lineId.Value, stopId.Value), lineName);

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Print(int? lineId, int? stopId)
        {
            return new ActionAsPdf("TimetableToPrint", new {lineId, stopId})
            {
                FileName = "rozklad.pdf",
                PageOrientation = Orientation.Landscape
            };
        }

    }
}

SIDUKM.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIDUKM</title>
    @Styles.Render("~/Content/dashgum")
    @RenderSection("AdditionalStyles", false)
    @Scripts.Render("~/bundles/modernizr")

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
        @RenderSection("PageStyles", false)
    </style>
</head>
<body>
    <section id="container">
        <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Ukryj/Pokaż menu"></div>
            </div>
            <!--logo start-->
            <a  href="@Url.Action("Index", "Home")" class="logo"><b>SIDUKM</b></a>
            <!--logo end-->
            @if (Context.User.Identity.IsAuthenticated)
            {
                <div class="top-menu " >
                 
                    <ul class="nav pull-right top-menu ">
                        <li>
                            <img width="40" height="40" class="img-circle" style="margin-top:10px" src="@Url.Action("GetAvatarByName", "Account", new { name = @Context.User.Identity.Name })" />
                        </li>
                        <li>
                            <p class="navbar-text">Witaj, <a href="@Url.Action("UserProfile", "Account", new { login=Context.User.Identity.Name })">@Context.User.Identity.Name</a>!</p>
                        </li>
                        <li>
                            <a class="logout" href="@Url.Action("EditAccount", "Account")">Edytuj</a>
                        </li>      
                        <li class="nav top-menu notify-row ">
                            
                            <a href="@Url.Action("List", "Message")">
                                <i class="fa fa-tasks" data-toggle="tooltip" title="Wiadomości">

                                </i>
                                @if (Html.Action("GetUnread", "Message").ToString() != "0")
                                {
                                    <span class="badge bg-theme">
                                        @Html.Action("GetUnread", "Message")
                                    </span>
                                }
                            </a>
                        </li>
                        <li>
                            <a class="logout" href="@Url.Action("Logout", "Account")">Wyloguj</a>
                        </li>
                    </ul>
                    <!--<p class="nav navbar-text pull-right top-menu">Witaj, @Context.User.Identity.Name</p>-->
                </div>
            }
        </header>

        <!--header end-->
        <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                  
                    <li class="mt">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="fa fa-home"></i>
                            <span>Strona główna</span>
                        </a>
                    </li>
                    
                    <li class="sub-menu">
                        <a href="@Url.Action("Index", "Spotted")">
                            <i class="fa fa-comment"></i>
                            <span>Spotted</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a href="@Url.Action("FindRoute", "Transport")">
                            <i class="fa fa-road"></i>
                            <span>Wyznacz trasę</span>
                        </a>
                    </li>
                    <li class="sub-menu">
                        <a href="@Url.Action("LinesList", "Transport")">
                            <i class="fa fa-book"></i>
                            <span>Rozkład jazdy</span>
                        </a>
                    </li>
                    @if (Context.User.IsInRole("Administrator"))
                    {
                        <li class="sub-menu">
                            <a href="@Url.Action("Menu", "Administration")">
                                <i class="fa fa-bitbucket"></i>
                                <span>Panel administratora</span>
                            </a>
                        </li>
                        <li class="sub-menu">
                            <a href="@Url.Action("Index", "Stats")">
                                <i class="fa fa-bar-chart"></i>
                                <span>Statystyki</span>
                            </a>
                        </li>
                    }
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper site-min-height">
                @RenderBody()
            </section><!-- /wrapper -->
        </section><!-- /MAIN CONTENT -->
        <!--main content end-->
        <!--footer start-->
        <footer class="grey-panel">
            <div class="text-center">
                2015 - SIDUKM
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    @Scripts.Render("~/bundles/jquery-bootstrap")
    @Scripts.Render("~/bundles/validation")
    @RenderSection("scripts", false)
    <script>
        //custom select box
        /*
        $(function () {
            $('select.styled').customSelect();
        });
        */
    </script>

    
</body>
</html>

SIDUKM.WebUI/Views/Shared/_Layout_old.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIDUKM</title>
    @Styles.Render("~/Content/css")
    @RenderSection("AdditionalStyles", false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SIDUKM", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("Użytkownik", "About", "Home")</li>
                    <li>@Html.ActionLink("Admin", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <p class="navbar-text">Witaj, @Context.User.Identity.Name</p>
                        <li>@Html.ActionLink("Wyloguj", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Logowanie", "Login", "Account")</li>
                        <li>@Html.ActionLink("Rejestracja", "Register", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SIDUKM</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>