SIDUKM.WebUI/Models/Account/EditAccountViewModel.cs
using SIDUKM.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SIDUKM.WebUI.Models.Account
{
    public class EditAccountViewModel
    {
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int AccountId { get; set; }
        [EmailAddress]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        //[Required(ErrorMessage = "To pole jest wymagane!")]
        public string Email { get; set; }

        [Display(Name = "Hasło")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Nowe hasło")]
        [DataType(DataType.Password)]
        [RegularExpression(@"(([0-9]).*([a-zA-z]).*)|(([a-zA-z]).*([0-9]).*)", ErrorMessage = "Hasło musi się składać z  minimum 6 znaków w tym jednej cyfry oraz jednej litery. i nie może być dłuższe niż 30 znaków")]
        public string NewPassword { get; set; }

        [Display(Name = "Powtórz hasło")]
        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "Hasła nie są zgodne")]
        public string RepeatPassword { get; set; }

        

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public List<Gender> Gender { get; set; }

        public short? GenderId { get; set; }

        public List<City> City { get; set; }

        public int CityId { get; set; }

        public List<UserRole> UserRole { get; set; }
        public int UserRoleId { get; set; }

        public string PreviousPage { get; set; }
      /*  public byte [] Avatar { get; set;}

       // [HiddenInput(DisplayValue=false)]
        public string MimeType { get; set;}
        */
      
    }
}

SIDUKM.WebUI/Models/Administration/AddLineViewModel.cs
using SIDUKM.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SIDUKM.WebUI.Models.Administration
{
    public class AddLineViewModel
    {
        [Required(ErrorMessage = "To pole jest wymagane!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane!")]
        public string Direction { get; set; }
        //public int LineTypeID { get; set; }
        //public List<LineType> LineType { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane!")]
        public int CityID { get; set; }
        //public List<string> Route { get; set; }
        public List<City> City { get; set; }
        /*public List<string> Stops { get; set; }
        public List<int> StopsID{get;set;}*/
    }
}

SIDUKM.WebUI/Models/Administration/AddTimetableViewModel.cs
using SIDUKM.Domain;
using System.Collections.Generic;

namespace SIDUKM.WebUI.Models.Administration
{
    public class AddTimetableViewModel
    {
        public int LineNumberID { get;set;}
        //public List<LineNumber> LineNuber{get;}
        public int StopID { get; set; }
        //public List<Stop> Stop{get;}
        //[RegularExpression(@"([0-5][0-9][A-Za-z\*]?\s?){0,}",ErrorMessage=@"Błąd! Prawidłowy wpis jednej danej: [0-5][0-9][A-Za-z\*]")]
        public List<string> TimetableNormal { get; set; }
        //[RegularExpression(@"([0-5][0-9][A-Za-z\*]?\s?){0,}", ErrorMessage = @"Błąd! Prawidłowy wpis jednej danej: [0-5][0-9][A-Za-z\*]")]
        public List<string> TimetableSaturday { get; set; }
        //[RegularExpression(@"([0-5][0-9][A-Za-z\*]?\s?){0,}", ErrorMessage = @"Błąd! Prawidłowy wpis jednej danej: [0-5][0-9][A-Za-z\*]")]
        public List<string> TimetableSunday { get; set; }
        public List<Stop> Stops { get; set; }
        public List<Line> Lines { get; set; }
    }
}

SIDUKM.WebUI/Models/Administration/BanViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SIDUKM.WebUI.Models.Administration
{
    public class BanViewModel
    {
        public int AccountId { get; set; }

        [Required(ErrorMessage = "Należy podać początkową datę!")]
        [DisplayName("Początkowa data bana")]
        [RegularExpression(@"\d\d\d\d\-\d\d\-\d\d", ErrorMessage = "Prawidłowy format daty: YYYY-MM-DD")]
        public string StartDate { get; set; }

        [Required(ErrorMessage = "Należy podać końcową datę!")]
        [DisplayName("Końcowa data bana")]
        [RegularExpression(@"\d\d\d\d\-\d\d\-\d\d", ErrorMessage = "Prawidłowy format daty: YYYY-MM-DD")]
        public string StopDate { get; set; }

        public string ReturnLink { get; set; }
        public string Username { get; set; }
    }
}

SIDUKM.WebUI/Controllers/AdministrationController.cs
using System.Linq;
using System.Web.Mvc;
using SIDUKM.Domain;
using SIDUKM.Logic;
using SIDUKM.WebUI.Infrastructure;
using SIDUKM.WebUI.Models.Administration;
using System.Globalization;
using System.Collections.Generic;
using System.IO.Compression;
using System;
using Newtonsoft.Json;

namespace SIDUKM.WebUI.Controllers
{
    public class AdministrationController : AbstractController
    {
        IBusService BusService { get; set; }
         delegate string ProcessTask(string id);
         ProgressManager Progress { get; set; }

        public AdministrationController(ISessionManager sessionManager, IAccountService accountService, IMailService mailService, IBusService busService) :
            base(sessionManager, accountService, mailService)
        {
            BusService = busService;
            Progress = new ProgressManager(busService);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Menu()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult UserList(string view)// by zwrocil jakis widok.
        {
            switch(view)
            {
                case "DefaultView": ViewBag.TitleLocal = "Lista aktywnych użytkowników"; break;
                case "ArchiveView": ViewBag.TitleLocal = "Archiwum kont użytkowników"; break;
                case "GuidView": ViewBag.TitleLocal = "Konta użytkowników z aktywnym przypomnieniem hasła"; break;
                case "BannedView": ViewBag.TitleLocal = "Lista zbanowych użytkowników"; break;
                default: ViewBag.TitleLocal = "Lista aktywnych użytkowników"; break;
            }
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult UserListData()  // jquery datatble && json wypelnia tabelke
        {
            string selectedView = "DefaultView";
            if(Request.UrlReferrer != null && Request.UrlReferrer.Query != "")
            {
                selectedView = Request.UrlReferrer.Query.Substring("view".Length + 2);
            }
            //ViewBag.SelectedView = selectedView;
            var collection = AccountService.GetAccountsData(selectedView);
            var parser = new DataTablesParser.DataTablesParser<AccountData>(Request, collection);
            return Json(parser.Parse());//,"application/json; charset=utf-8", JsonRequestBehavior.AllowGet);
            /* JsonResult r =  new JsonResult() { JsonRequestBehavior = JsonRequestBehavior.DenyGet, Data = new { data = collection } };
                   return r; }*/
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult EditAccount(int id, string view)
        {
            Account acc = AccountService.GetAccountById(id, false);
            if (acc == null)
            {
                return View();
            }
            var model = new EditAccountViewModel()
            {
                ReturnLink = Request.ServerVariables["HTTP_REFERER"],
                AccountId = id,
                UserRole = AccountService.GetUserRoles().ToList(),
                UserRoleId = acc.UserRoleId ?? 1
            };
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult EditAccount(EditAccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                /*Account account = AccountService.GetAccountById(model.AccountId); //tylko po to by wyciagnac login do result
                if(account == null)
                {
                    ViewBag.isEdited = 2;
                    return View(model);
                }*/
                /*Account result = new Account
                {
                    AccountId = acc.AccountId,
                    AccountLogin = account.AccountLogin,
                    AccountPassword = acc.NewPassword,
                    CityId = (short) acc.CityID,
                    Email = acc.Email,
                    FirstName = acc.Name,
                    GenderId = acc.SexID,
                    LastName = acc.SurName,
                    UserRoleId = (short) acc.UserRoleID
                };

                AccountAvatar newAccountAvatar = null;
                if(avatar != null)
                {
                    newAccountAvatar = new AccountAvatar
                    {
                        AccountId = acc.AccountId,
                        MimeType = avatar.ContentType,
                        Avatar = new byte [avatar.ContentLength]
                    };
                    avatar.InputStream.Read(newAccountAvatar.Avatar, 0, avatar.ContentLength);
                }

                acc.Sex = AccountService.GetGenders().ToList();
                acc.City = AccountService.GetCities().ToList();
                acc.UserRole = AccountService.GetUserRoles().ToList();

                bool isEdited = AccountService.EditAccount(result, newAccountAvatar);
                ViewBag.isEdited = isEdited ? 1 : 2;

                if(isEdited) return RedirectToAction("UserList");*/
                bool isEdited = AccountService.ChangeUserRole(model.AccountId, model.UserRoleId);
                ViewBag.isEdited = isEdited ? 1 : 2;
                if (isEdited)
                {
                    //return RedirectToAction("UserList");
                    return Redirect(model.ReturnLink);
                }
                return View(model);
            }
            /*acc.Sex = AccountService.GetGenders().ToList();
            acc.City = AccountService.GetCities().ToList();*/
            model.UserRole = AccountService.GetUserRoles().ToList();
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult DeleteAccount(int id)
        {
            var result = AccountService.DeleteAccount(id);
            return RedirectToAction("UserList");
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult DeleteAvatar(int id)
        {
            var result = AccountService.DeleteAvatar(id);
            return RedirectToAction("EditAccount");
        }

        [Authorize(Roles = "Administrator")]
        [HttpGet]
        public ActionResult GetAccountName(int id)
        {
            var result = AccountService.GetAccountById(id);
            return Content(result.AccountLogin);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddStop()
        {
            var model = new SIDUKM.WebUI.Models.Administration.StopViewModel();
            model.City = AccountService.GetCities().ToList();
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult AddStop(StopViewModel model)
        {
            if(ModelState.IsValid)
            {
                var newStop = new Stop()
                {
                    CityId = (short) model.CityID,
                    CoordinateX = model.CoordinateX.ToString(CultureInfo.InvariantCulture),
                    CoordinateY = model.CoordinateY.ToString(CultureInfo.InvariantCulture),
                    StopName = model.Name,
                    StopNumber = model.Number
                };
                bool isAdded = BusService.AddOrUpdateStop(newStop);
                ViewBag.completed = isAdded;
                if(isAdded)
                {
                    model = new StopViewModel();
                    ModelState.Clear();
                }
                model.City = AccountService.GetCities().ToList();
                return View(model);
            }
            else
            {
                model.City = AccountService.GetCities().ToList();
                return View(model);
            }
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddLine()
        {
            var model = new SIDUKM.WebUI.Models.Administration.AddLineViewModel();
            model.City = AccountService.GetCities().ToList();
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        [HttpPost]
        public ActionResult AddLine(AddLineViewModel model)
        {
            if(ModelState.IsValid)
            {
                var newLine = new Line()
                {
                    CityId = (short) model.CityID,
                    Direction = model.Direction,
                    LineName = model.Name
                };
                bool isSuccess = BusService.AddOrUpdateLine(newLine);
                ViewBag.comp = isSuccess;
                if(isSuccess)
                {
                    model = new AddLineViewModel();
                    ModelState.Clear();
                }
                model.City = AccountService.GetCities().ToList();
                return View(model);
            }
            else
            {
                model.City = AccountService.GetCities().ToList();
                return View(model);
            }
        }

       /* [Authorize(Roles = "Administrator")]
        public ActionResult AddTimetable()
        {
            AddTimetableViewModel model = new AddTimetableViewModel();
            // TODO podział w zależności od miasta
            model.Stops = BusService.GetStops(1).ToList();
            model.Lines = BusService.GetLines(1).ToList();
            return View(model);
        }*/

        [Authorize(Roles = "Administrator")]
        public ActionResult AddTimetable(int lineId=1, int stopId=2)
        {
            
            AddTimetableViewModel model = new AddTimetableViewModel()
            {
                //Stops = BusService.GetStops(1).ToList(),
                Lines = BusService.GetLines(1).ToList(),
                Stops = BusService.GetSortedStops(lineId),
                LineNumberID = lineId,
                StopID = stopId,          

SIDUKM.WebUI/Controllers/StatsController.cs
using System.Linq;
using System.Web.Mvc;
using SIDUKM.Logic;
using SIDUKM.WebUI.Infrastructure;

namespace SIDUKM.WebUI.Controllers
{
    public class StatsController : AbstractController
    {
        IStatService StatService { get; set; }

        public StatsController(ISessionManager sessionManager, IAccountService accountService, IMailService mailService,
            IStatService statService) : base(sessionManager, accountService, mailService)
        {
            StatService = statService;
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetRegistrationsPerDay(int acc = 0)
        {
            var result = acc == 0
                ? StatService.RegistrationsPerDay().OrderBy(x => x.Key)
                : StatService.StatAccumulated(StatService.RegistrationsPerDay)
                    .OrderBy(x => x.Key);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetTopicsPerDay(int acc = 0)
        {
            var result = acc == 0
                ? StatService.SpottedTopicsPerDay().OrderBy(x => x.Key)
                : StatService.StatAccumulated(StatService.SpottedTopicsPerDay)
                    .OrderBy(x => x.Key);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetPostsPerDay(int acc = 0)
        {
            var result = acc == 0
                ? StatService.SpottedPostsPerDay().OrderBy(x => x.Key)
                : StatService.StatAccumulated(StatService.SpottedPostsPerDay)
                    .OrderBy(x => x.Key);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetMostCommented()
        {
            return Json(StatService.MostCommentedTopic(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetTopicVotes(int type = 1)
        {
            return type == -1
                ? Json(StatService.LowestVotesTopic(), JsonRequestBehavior.AllowGet)
                : Json(StatService.HighestVotesTopic(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetPostVotes(int type = 1)
        {
            return type == -1
                ? Json(StatService.LowestVotesPost(), JsonRequestBehavior.AllowGet)
                : Json(StatService.HighestVotesPost(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrator")]
        public JsonResult GetActivity(int posts = 0, int count = 10)
        {
            return posts == 1
                ? Json(StatService.SpottedActivityByPosts(count).OrderByDescending(x => x.Value),
                    JsonRequestBehavior.AllowGet)
                : Json(StatService.SpottedActivityByTopics(count).OrderByDescending(x => x.Value),
                    JsonRequestBehavior.AllowGet);
        }
    }
}

SIDUKM.WebUI/Views/Administration/EditAccount.cshtml
@model SIDUKM.WebUI.Models.Administration.EditAccountViewModel
@{
    ViewBag.Title = "Edycja konta";
}
@*@section scripts{
    @Scripts.Render("~/bundles/avatar")
    }*@

<h2>Edycja konta</h2>

<hr />
@if(ViewBag.isEdited == null)
{
    using(Html.BeginForm("EditAccount", "Administration"))
    {
   
    @*<div class="form-group row " style="padding:10px">
            @Html.Label("Adres e-mail ", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
            @Html.TextBoxFor(m => Model.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => Model.Email)
        </div>*@
        <div class="form-group row " style="padding:10px">
            @Html.Label("Rola użytkownika ", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
            @Html.DropDownListFor(m => m.UserRoleId , new SelectList(Model.UserRole , "UserRoleId", "RoleName"), new { @class = "form-control" })
        </div>
        @*<div class="form-group row " style="padding:10px">
        @Html.Label("Nowe hasło ", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
        @Html.PasswordFor(m => Model.NewPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => Model.NewPassword)
    </div>
    <div class="form-group row " style="padding:10px">
        @Html.Label("Powtórz nowe hasło ", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
        @Html.PasswordFor(m => Model.RepeatPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => Model.RepeatPassword)
    </div>
    <hr />

    <div class="form-group row " style="padding:10px">
        @Html.Label("Imię", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
        @Html.TextBoxFor(m => Model.Name, new { @class = "form-control" })
    </div>
    <div class="form-group row " style="padding:10px">
        @Html.Label("Nazwisko", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
        @Html.TextBoxFor(m => Model.SurName, new { @class = "form-control" })
    </div>
    <div class="form-group row " style="padding:10px">
        @Html.Label("Płeć", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
        @Html.DropDownListFor(m => m.SexID, new SelectList(Model.Sex, "GenderId", "GenderName"), new { @class = "form-control" })
    </div>
    <div class="form-group row " style="padding:10px">
        @Html.Label("Miasto", new { @class = "control-label col-xs-12 col-sm-4 col-md-3 col-lg-2" })
        @Html.DropDownListFor(m => m.CityID, new SelectList(Model.City, "CityId", "CityName"), new { @class = "form-control" })
    </div>
*@
         @Html.HiddenFor(m => m.AccountId) 
        @Html.HiddenFor(m=>m.ReturnLink)
    @*
        <!-- Avatar Column-->
        <div class="row" style="padding:10px">
            <div class="col-md-2">
                @Html.Label("Awatar", new { @class = "control-label" })
            </div>
            <div class="col-md-4">
                <div class="row">
                    <div class="col-md-4">
                        <img width="100" height="100" src="@Url.Action("GetAvatar","Account", new { id = Model.AccountId })" id="avatar_img"/>
                    </div>
                    <div class="col-md-8">
                        <input type="file" name="avatar" accept="image/*" id="avatar_upload"/>
                        <button id="btnRemove" type="button" onClick="openModal()" class="btn btn-primary btn-info" data-toggle="modal" data-target="#myModal" style="margin-top:30px"> Usuń </button>
                    </div>
                </div>
            </div>
            <div class="col-md-2"> </div> <!-- zamiast tego jakis offset -->
        </div>*@

        <!-- Buttons-->
        <button type="submit" class="btn btn-primary">Zastosuj</button>
        //@Html.ActionLink("Powrót", "UserList", "Administration", null, new {@class = "btn btn-default btn-md"})
        <a href="@Model.ReturnLink" class="btn btn-default btn-md">Powrót</a>
     }

      @*  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Usuwanie awatara</h4>
                </div>
                <div class="modal-body">
                    Czy na pewno chcesz usunąć awatar użytkownika?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Nie</button>
                    <button type="button" class="btn btn-primary">Tak</button>
                </div>
            </div>
        </div>
    </div> *@

}
else if (ViewBag.isEdited == 1)
{
        <h2>Pomyślnie zedytowano!</h2>
    }
    else
    {
        <h2>Wystąpił błąd przy edycji konta! Spróbuj ponownie.</h2>
    }

SIDUKM.WebUI/Views/Administration/Menu.cshtml
@{
    ViewBag.Title = "Panel Administratora - Menu";
}

@section AdditionalStyles { @Styles.Render("~/Content/DropDownPanel") }

<section>
    <header>
        <h2 class="text-center"> Panel administratora </h2>
    </header>
</section>
<hr />
<div class="container">
    <div class="row">
        
        <div class="col-md-6 col-md-offset-3">

            <!-- Użytkownicy-->
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="clickable">
                        <i class="pull-left fa fa-minus"></i>
                        <h3 class="panel-title">Użytkownicy</h3>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-user-md fa-3x"></i>
                            <div>
                                @Html.ActionLink("Lista użytkowników", "UserList", "Administration", new { view = "DefaultView" }, null)
                               
                            </div>
                        </div>

                        <div class="col-md-6 text-center">
                            <i class="fa fa-lock fa-3x"></i>
                            <div>
                                @Html.ActionLink("Zablokowani użytkownicy", "UserList", "Administration", new { view = "BannedView" }, null)
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-link fa-3x"></i>
                            <div>
                                @Html.ActionLink("Pokaż konta z aktywnym przypomnieniem hasła", "UserList", "Administration", new { view = "GuidView" }, null)
                            </div>
                        </div>

                        <div class="col-md-6 text-center">
                            <i class="fa fa-archive fa-3x"></i>
                            <div>
                                @Html.ActionLink("Archiwum", "UserList", "Administration", new { view = "ArchiveView" }, null)
                            </div>
                        </div>
                    </div>
                 </div>
            </div>

            <!-- Spotted-->
            <!----<div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="clickable">
                        <i class="pull-left fa fa-minus"></i>
                        <h3 class="panel-title">Spotted</h3>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-cloud fa-3x"></i>
                            <div>
                                <p>Zarządzaj wpisami użytkowników</p>
                            </div>
                        </div>-->
                            <!-- next item here  :)-->
                    <!----</div>
                </div>
            </div>--->

             <!-- Trasy i rozkłady-->
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="clickable">
                        <i class="pull-left fa fa-minus"></i>
                        <h3 class="panel-title">Trasy i rozkłady</h3>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-arrows-h fa-3x"></i>
                            <div>
                                @Html.ActionLink("Dodaj linię", "AddLine", "Administration", new { view = "LineView" }, null)
                            </div>
                        </div>
                        <div class="col-md-6 text-center">
                            <i class="fa fa-arrow-circle-up fa-3x"></i>
                            <div>
                                @Html.ActionLink("Dodaj przystanek", "AddStop", "Administration", new { view = "StopView" }, null)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-road fa-3x"></i>
                            <div>
                                @Html.ActionLink("Dodaj rozkład jazdy", "AddTimeTable", "Administration", new {view = "TimetableView"}, null)
                            </div>
                        </div>
                        <!--<div class="col-md-6 text-center">
                            <i class="fa fa-code-fork fa-3x"></i>
                            <div>
                                <p>Lista tras</p>
                            </div>
                        </div>-->
                        <div class="col-md-6 text-center">
                            <i class="fa fa-cloud-download fa-3x"></i>
                            <div>
                                @Html.ActionLink("Pobierz rozkłady", "DownloadTimeTable", "Administration")
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

           <!-- Inne-->
            <!----<div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="clickable">
                        <i class="pull-left fa fa-minus"></i>
                        <h3 class="panel-title">Inne</h3>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-bank fa-3x"></i>
                            <div>
                                <p>Lista Miast</p>
                            </div>
                        </div>

                        <div class="col-md-6 text-center">
                            <i class="fa fa-desktop fa-3x"></i>
                            <div>
                                <p>Przystanki</p>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 text-center">
                            <i class="fa fa-bar-chart-o fa-3x"></i>
                            <div>
                                @@Html.ActionLink("Statystyki", "Stats", "Home", null)
                            </div>
                        </div>-->
                       <!-- next item here :)-->
                    <!----</div>-->

                </div>
            </div>
         </div>
     </div>
</div>


                    
                                
                              
                            
                        